version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: pealo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - pealo-db-data:/data/db
    restart: unless-stopped

volumes:
  pealo-db-data:
    driver: local
